version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app.py:/app/app.py
      - ./common.py:/app/common.py
      - ./utils.py:/app/utils.py
      - ./routes:/app/routes